INSERT INTO `Order` (description,ship_from_address,ship_type,close_type) VALUES ('Order Description','48535  Armenia Ave.','ship type 1','2012-05-09');
INSERT INTO `Order` (description,ship_from_address,ship_type,close_type) VALUES ('Order Description','70821  Malta Ln.','ship type 1','2012-05-04');
INSERT INTO `Order` (description,ship_from_address,ship_type,close_type) VALUES ('Order Description','6088 North Saint Helena Blvd.','ship type 1','2012-05-07');
INSERT INTO `Order` (description,ship_from_address,ship_type,close_type) VALUES ('Order Description','47012 South Colombia Ave.','ship type 1','2012-05-08');
INSERT INTO `Order` (description,ship_from_address,ship_type,close_type) VALUES ('Order Description','59442 West Canada Ct.','ship type 2','2012-05-08');
INSERT INTO `Order` (description,ship_from_address,ship_type,close_type) VALUES ('Order Description','5872 West Pitcairn Way','ship type 2','2012-05-10');
INSERT INTO `Order` (description,ship_from_address,ship_type,close_type) VALUES ('Order Description','63581 West Dominican Republic St.','ship type 3','2012-05-10');
INSERT INTO `Order` (description,ship_from_address,ship_type,close_type) VALUES ('Order Description','37655 North Mozambique Way','Etiam','2012-05-06');
INSERT INTO `Order` (description,ship_from_address,ship_type,close_type) VALUES ('Order Description','82681 West Evansville Blvd.','ship type 3','2012-05-10');
INSERT INTO `Order` (description,ship_from_address,ship_type,close_type) VALUES ('Order Description','43071  Mequon Blvd.','ship type 1','2012-05-07');