INSERT INTO Company (name,address,company_type,email,phone) VALUES ('Fruit of the Loom','54423 North Argentina Ct.','dapibus','Wylie@parturient.net','111-457-4485');
INSERT INTO Company (name,address,company_type,email,phone) VALUES ('General Mills','6121  Fontana Blvd.','Cras','Daryl@malesuada.gov','848-820-6926');
INSERT INTO Company (name,address,company_type,email,phone) VALUES ('British Petroleum','89629 East Guinea-bissau Way','tortor','Andrew@natoque.org','011-176-6077');
INSERT INTO Company (name,address,company_type,email,phone) VALUES ('Jansport','74020 South Bosnia and Herzegovina Way','ad','Wynter@Vestibulum.edu','301-383-0422');
INSERT INTO Company (name,address,company_type,email,phone) VALUES ('Fake Company','34227 West Chad Ct.','parturient','Rhea@ridiculus.gov','780-633-9521');
INSERT INTO Company (name,address,company_type,email,phone) VALUES ('Test company','20099 South Dominica St.','Morbi','Yen@morbi.us','156-653-3683');
INSERT INTO Company (name,address,company_type,email,phone) VALUES ('Nabisco','12120 South Opelousas Ct.','cursus','Colby@Curae.org','043-420-8162');
INSERT INTO Company (name,address,company_type,email,phone) VALUES ('Mirimax','4228 West Anderson St.','rhoncus','Caldwell@non.us','882-739-8714');
INSERT INTO Company (name,address,company_type,email,phone) VALUES ('Hershey','2709 West Turks and Caicos Islands Ave.','In','Austin@erat.gov','944-719-8358');
INSERT INTO Company (name,address,company_type,email,phone) VALUES ('Tester','38272 North Uzbekistan St.','magnis','Leila@imperdiet.us','623-318-3531');
