INSERT INTO Product (name,description,product_type,price) VALUES ('Pencils','Box','Writing',0.93);
INSERT INTO Product (name,description,product_type,price) VALUES ('Pineapple','Whole','Produce',3.64);
INSERT INTO Product (name,description,product_type,price) VALUES ('Strawberry','Flat','Produce',4.33);
INSERT INTO Product (name,description,product_type,price) VALUES ('Pens','Blue','Box',3.09);
INSERT INTO Product (name,description,product_type,price) VALUES ('Oreos','Chocolate and Creme Filled Cookies','Dessert',3.71);
INSERT INTO Product (name,description,product_type,price) VALUES ('Flatscreen','23inch','Monitor',382.06);
INSERT INTO Product (name,description,product_type,price) VALUES ('Ram','DDR3-2400 ','Computer',50.04);
INSERT INTO Product (name,description,product_type,price) VALUES ('Chicken','Boneless, skinless chicken breast','Meat',4.52);
INSERT INTO Product (name,description,product_type,price) VALUES ('Apple Jacks','A delicious low calorie meal','Cereal',3.04);
INSERT INTO Product (name,description,product_type,price) VALUES ('Mighty Taco','A late-night taco.','Southwestern',1.23);
INSERT INTO Product (name,description,product_type,price) VALUES ('Pork','Porkchops','Meat',4.04);
INSERT INTO Product (name,description,product_type,price) VALUES ('Cherries','Bag','Produce',4.23);
INSERT INTO Product (name,description,product_type,price) VALUES ('Ibuprofen','used to relieve pain, tenderness, swelling, and stiffness','Pharmaceutical',4.04);
INSERT INTO Product (name,description,product_type,price) VALUES ('Acetaminophen','Acetaminophen is used to relieve mild to moderate pain from headaches, muscle aches','Pharmaceutical',4.23);
INSERT INTO Product (name,description,product_type,price) VALUES ('Harddrive','7200 RPM SATA ','Computer',60.03);
INSERT INTO Product (name,description,product_type,price) VALUES ('Reeses Puffs','A sugary way to start the day ','Cereal',3.10);
INSERT INTO Product (name,description,product_type,price) VALUES ('Cinnamon Toast Crunch','The taste you can see ','Cereal',3.05);
INSERT INTO Product (name,description,product_type,price) VALUES ('Honey Nut Cheerios','A variaton of cheerios ','Cereal',3.05);
INSERT INTO Product (name,description,product_type,price) VALUES ('Ketchup','A  sweet-and-tangy food sauce ','Condiment',2.05);
INSERT INTO Product (name,description,product_type,price) VALUES ('BBQ Sauce ','A  smokey, flavorful food sauce ','Condiment',2.15);
